version: '3'

services:

  nats-server:
    image: nats:latest # En producción debería ser nats:etiqueta_version_123
    ports:
      - "8222:8222"

  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: southamerica-west1-docker.pkg.dev/tienda-microservices-440713/image-registry/client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    # volumes:
    #   - ./client-gateway/src:/usr/src/app/src
    # command: npm run start:dev
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=nats://nats-server:4222

  products-ms:
    build:
      context: ./products-ms
      dockerfile: dockerfile.prod
    image: southamerica-west1-docker.pkg.dev/tienda-microservices-440713/image-registry/products-ms
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db

  orders-ms:
    build: 
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}
    image: southamerica-west1-docker.pkg.dev/tienda-microservices-440713/image-registry/orders-ms
    environment:
      - PORT=3000
      - DATABASE_URL=${ORDERS_DATABASE_URL}
      - NATS_SERVERS=nats://nats-server:4222

# # ===================================================== #
# # Payments Microservice #
# # ===================================================== #
  payments-ms:
    build:
      context: ./payments-ms
      dockerfile: dockerfile.prod
    image: southamerica-west1-docker.pkg.dev/tienda-microservices-440713/image-registry/payments-ms
    ports: 
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}

# # ===================================================== #
# # Auth Microservice #
# # ===================================================== #
  auth-ms:
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
    image: southamerica-west1-docker.pkg.dev/tienda-microservices-440713/image-registry/auth-ms
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}